# 'api': {
#                 'public': {
#                     'get': {
#                         'market/tickers': 1,
#                         'market/ticker': 1,
#                         'market/index-tickers': 1,
#                         'market/books': 1,
#                         'market/books-lite': 1.66,
#                         'market/candles': 0.5,
#                         'market/history-candles': 1,
#                         'market/history-mark-price-candles': 2,
#                         'market/history-index-candles': 2,
#                         'market/index-candles': 1,
#                         'market/mark-price-candles': 1,
#                         'market/trades': 1,
#                         'market/platform-24-volume': 10,
#                         'market/open-oracle': 40,
#                         'market/index-components': 1,
#                         'market/option/instrument-family-trades': 1,
#                         # 'market/oracle',
#                         'public/instruments': 1,
#                         'public/instrument-tick-bands': 4,
#                         'public/delivery-exercise-history': 0.5,
#                         'public/open-interest': 1,
#                         'public/funding-rate': 1,
#                         'public/funding-rate-history': 1,
#                         'public/price-limit': 1,
#                         'public/opt-summary': 1,
#                         'public/estimated-price': 2,
#                         'public/discount-rate-interest-free-quota': 10,
#                         'public/time': 2,
#                         'public/liquidation-orders': 0.5,
#                         'public/mark-price': 2,
#                         'public/option-trades': 1,
#                         # 'public/tier',
#                         'public/position-tiers': 2,
#                         'public/underlying': 1,
#                         'public/interest-rate-loan-quota': 10,
#                         'public/vip-interest-rate-loan-quota': 10,
#                         'rubik/stat/trading-data/support-coin': 4,
#                         'rubik/stat/taker-volume': 4,
#                         'rubik/stat/margin/loan-ratio': 4,
#                         # long/short
#                         'rubik/stat/contracts/long-short-account-ratio': 4,
#                         'rubik/stat/contracts/open-interest-volume': 4,
#                         'rubik/stat/option/open-interest-volume': 4,
#                         # put/call
#                         'rubik/stat/option/open-interest-volume-ratio': 4,
#                         'rubik/stat/option/open-interest-volume-expiry': 4,
#                         'rubik/stat/option/open-interest-volume-strike': 4,
#                         'rubik/stat/option/taker-block-volume': 4,
#                         'system/status': 100,
#                         'finance/savings/lending-rate-summary': 5 / 3,
#                         'finance/savings/lending-rate-history': 5 / 3,
#                         'market/exchange-rate': 20,
#                     },
#                 },
#                 'private': {
#                     'get': {
#                         'account/account-position-risk': 2,
#                         'account/balance': 2,
#                         'account/positions': 2,
#                         'account/positions-history': 2,
#                         'account/bills': 5 / 3,
#                         'account/bills-archive': 5 / 3,
#                         'account/config': 4,
#                         'account/max-size': 1,
#                         'account/max-avail-size': 1,
#                         'account/leverage-info': 1,
#                         'account/max-loan': 1,
#                         'account/trade-fee': 4,
#                         'account/interest-accrued': 4,
#                         'account/interest-rate': 4,
#                         'account/max-withdrawal': 1,
#                         'account/risk-state': 2,
#                         'account/borrow-repay-history': 4,
#                         'account/quick-margin-borrow-repay-history': 4,
#                         'account/interest-limits': 4,
#                         'account/vip-interest-accrued': 4,
#                         'account/vip-loan-order-list': 4,
#                         'account/vip-loan-order-detail': 4,
#                         'asset/asset-valuation': 1 / 5,
#                         'asset/deposit-address': 5 / 3,
#                         'asset/balances': 5 / 3,
#                         'asset/transfer-state': 10,
#                         'asset/deposit-history': 5 / 3,
#                         'asset/withdrawal-history': 5 / 3,
#                         'asset/deposit-withdraw-status': 20,
#                         'asset/currencies': 5 / 3,
#                         'asset/bills': 5 / 3,
#                         'asset/piggy-balance': 5 / 3,
#                         'asset/deposit-lightning': 5,
#                         'asset/non-tradable-assets': 5 / 3,
#                         'trade/order': 1 / 3,
#                         'trade/orders-pending': 1,
#                         'trade/orders-history': 0.5,
#                         'trade/orders-history-archive': 1,
#                         'trade/fills': 1 / 3,
#                         'trade/fills-history': 2,
#                         'trade/orders-algo-pending': 1,
#                         'trade/orders-algo-history': 1,
#                         'trade/order-algo': 1,
#                         'account/subaccount/balances': 10,
#                         'account/subaccount/interest-limits': 4,
#                         'asset/subaccount/bills': 5 / 3,
#                         'users/subaccount/list': 10,
#                         'users/subaccount/apikey': 10,
#                         'users/entrust-subaccount-list': 10,
#                         # broker
#                         'broker/nd/info': 10,
#                         'broker/nd/subaccount-info': 10,
#                         'asset/broker/nd/subaccount-deposit-address': 4,
#                         'asset/broker/nd/subaccount-deposit-history': 4,
#                         'broker/nd/rebate-daily': 1,
#                         'broker/nd/subaccount/apikey': 10,
#                         'broker/nd/rebate-per-orders': 300,
#                         'asset/broker/nd/subaccount-withdrawal-history': 4,
#                         # convert
#                         'asset/convert/currencies': 5 / 3,
#                         'asset/convert/currency-pair': 5 / 3,
#                         'asset/convert/estimate-quote': 5,
#                         'asset/convert/trade': 5,
#                         'asset/convert/history': 5 / 3,
#                         # options
#                         'account/greeks': 2,
#                         # earn
#                         'finance/staking-defi/offers': 1,
#                         'finance/staking-defi/orders-active': 1,
#                         'finance/staking-defi/orders-history': 1,
#                         'finance/savings/balance': 5 / 3,
#                         'finance/savings/lending-history': 5 / 3,
#                         'rfq/counterparties': 4,
#                         'rfq/maker-instrument-settings': 4,
#                         'rfq/rfqs': 10,
#                         'rfq/quotes': 10,
#                         'rfq/trades': 4,
#                         'rfq/public-trades': 4,
#                         # copytrading
#                         'copytrading/current-subpositions': 10,
#                         'copytrading/subpositions-history': 10,
#                         'copytrading/instruments': 10,
#                         'copytrading/profit-sharing-details': 10,
#                         'copytrading/total-profit-sharing': 10,
#                         'copytrading/unrealized-profit-sharing-details': 10,
#                         # grid trading
#                         'tradingBot/grid/orders-algo-pending': 1,
#                         'tradingBot/grid/orders-algo-history': 1,
#                         'tradingBot/grid/orders-algo-details': 1,
#                         'tradingBot/grid/sub-orders': 1,
#                         'tradingBot/grid/positions': 1,
#                         'tradingBot/grid/ai-param': 1,
#                     },
#                     'post': {
#                         'account/set-position-mode': 4,
#                         'account/set-leverage': 1,
#                         'account/position/margin-balance': 1,
#                         'account/set-greeks': 4,
#                         'account/set-isolated-mode': 4,
#                         'account/set-riskOffset-type': 2,
#                         'account/simulated_margin': 10,
#                         'account/borrow-repay': 5 / 3,
#                         'account/quick-margin-borrow-repay': 4,
#                         'account/activate-option': 4,
#                         'account/set-auto-loan': 4,
#                         'account/subaccount/set-loan-allocation': 4,
#                         'asset/transfer': 10,
#                         'asset/withdrawal': 5 / 3,
#                         'asset/withdrawal-lightning': 5,
#                         'asset/cancel-withdrawal': 5 / 3,
#                         'asset/convert-dust-assets': 10,
#                         'trade/order': 1 / 3,
#                         'trade/batch-orders': 1 / 15,
#                         'trade/cancel-order': 1 / 3,
#                         'trade/cancel-batch-orders': 1 / 15,
#                         'trade/amend-order': 1 / 3,
#                         'trade/amend-batch-orders': 1 / 3,
#                         'trade/amend-algos': 1,
#                         'trade/close-position': 1,
#                         'trade/order-algo': 1,
#                         'trade/cancel-algos': 1,
#                         'trade/cancel-advance-algos': 1,
#                         'users/subaccount/delete-apikey': 10,
#                         'users/subaccount/modify-apikey': 10,
#                         'users/subaccount/apikey': 10,
#                         'users/subaccount/set-transfer-out': 10,
#                         'asset/subaccount/transfer': 10,
#                         # broker
#                         'broker/nd/create-subaccount': 10,
#                         'broker/nd/delete-subaccount': 10,
#                         'broker/nd/set-subaccount-level': 4,
#                         'broker/nd/set-subaccount-fee-rate': 4,
#                         'asset/broker/nd/subaccount-deposit-address': 4,
#                         'broker/nd/subaccount/apikey': 10,
#                         'broker/nd/subaccount/delete-apikey': 10,
#                         'broker/nd/subaccount/modify-apikey': 10,
#                         'broker/nd/rebate-per-orders': 36000,
#                         # earn
#                         'finance/staking-defi/purchase': 3,
#                         'finance/staking-defi/redeem': 3,
#                         'finance/staking-defi/cancel': 3,
#                         'finance/savings/purchase-redempt': 5 / 3,
#                         'finance/savings/set-lending-rate': 5 / 3,
#                         'rfq/create-rfq': 4,
#                         'rfq/cancel-rfq': 4,
#                         'rfq/cancel-batch-rfqs': 10,
#                         'rfq/cancel-all-rfqs': 10,
#                         'rfq/execute-quote': 10,
#                         'rfq/maker-instrument-settings': 4,
#                         'rfq/mmp-reset': 4,
#                         'rfq/create-quote': 0.4,
#                         'rfq/cancel-quote': 0.4,
#                         'rfq/cancel-batch-quotes': 10,
#                         'rfq/cancel-all-quotes': 10,
#                         # copytrading
#                         'copytrading/algo-order': 20,
#                         'copytrading/close-subposition': 10,
#                         'copytrading/set-instruments': 10,
#                         # grid trading
#                         'tradingBot/grid/order-algo': 1,
#                         'tradingBot/grid/amend-order-algo': 1,
#                         'tradingBot/grid/stop-order-algo': 1,
#                         'tradingBot/grid/withdraw-income': 1,
#                         'tradingBot/grid/compute-margin-balance': 1,
#                         'tradingBot/grid/margin-balance': 1,
#                     },
#                 },
#             },